jobs:
  publish-master:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: set release version
      run: echo "RELEASE_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate
        -Dexpression=project.version | grep -Ev 'Download|INFO|WARNING')" >> $GITHUB_ENV
    - continue-on-error: true
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - continue-on-error: true
      name: install deps
      run: pip3 install 'git+https://github.com/logicalclocks/feature-store-api@master#egg=hsfs[docs]&subdirectory=python'
    - continue-on-error: true
      name: setup git
      run: 'git config --global user.name Mike

        git config --global user.email mike@docs.hopsworks.ai

        '
    - continue-on-error: true
      name: mike deploy docs
      run: mike deploy ${{ env.RELEASE_VERSION }} latest -u --push
name: mkdocs-release
on:
  repository_dispatch:
    types: trigger-ga___mkdocs-release.yml
